import type { Order } from './types';

export const ORDERS_SEED: Order[] = [
  {
    id: 'RX-001', customer: 'Emily Johnson', phone: '(617) 555-0193',
    address: '142 Newbury St, Boston, MA 02116', deliveryType: 'courier', courier: 'DoorDash',
    status: 'new', payStatus: 'paid', payMethod: 'Visa',
    hasRx: true, rxStatus: 'pending',
    total: 110.95, deliveryFee: 6.99, time: '9:38 AM', timeAgo: '3m ago', phase: 0,
    msgs: [
      { from: 'buyer', text: 'Hi, can this be delivered before 11am?', time: '9:38', unread: true },
      { from: 'buyer', text: 'I have the original prescription — I\'ll hand it over at drop-off.', time: '9:39', unread: true },
    ],
    items: [
      { name: 'Augmentin 625mg', dose: '10 tabs', price: 45.00, qty: 10, packed: false, expiry: '08/2026', icon: 'medication' },
      { name: 'Vitamin C 1000mg', dose: '1 box', price: 12.99, qty: 1, packed: false, expiry: '12/2025', icon: 'dot' },
      { name: 'Cetirizine 10mg', dose: '1 box', price: 14.99, qty: 1, packed: false, expiry: '11/2026', icon: 'medication' },
      { name: 'Saline Nasal Spray', dose: '1 bottle', price: 8.99, qty: 1, packed: false, expiry: '10/2026', icon: 'bottleB' },
      { name: 'Omeprazole 20mg', dose: '14 caps', price: 18.99, qty: 14, packed: false, expiry: '07/2026', icon: 'dot' },
      { name: 'Acetaminophen 500mg', dose: '1 box', price: 9.99, qty: 1, packed: false, expiry: '03/2027', icon: 'medication' },
    ],
    note: 'Requires original prescription on delivery. Please call before dispatch because the buyer will hand over the physical prescription at drop-off, and requests pharmacist confirmation for dosage and expiry before packing.',
    actionType: 'accept',
  },
  {
    id: 'RX-002', customer: 'Michael Rodriguez', phone: '(212) 555-0147',
    address: '88 West 34th St, New York, NY 10001', deliveryType: 'courier', courier: 'Instacart',
    status: 'preparing', payStatus: 'paid', payMethod: 'Mastercard',
    hasRx: false, rxStatus: null,
    total: 209.79, deliveryFee: 8.99, time: '9:21 AM', timeAgo: '20m ago', phase: 2,
    msgs: [
      { from: 'pharmacy', text: 'Your order is being packed, ready in about 15 minutes.', time: '9:25', unread: false },
      { from: 'buyer', text: 'Thanks! Is it possible to switch to an afternoon delivery?', time: '9:30', unread: true },
    ],
    items: [
      { name: 'Tylenol Extra Strength 500mg', dose: '2 boxes', price: 11.98, qty: 2, packed: true, expiry: '03/2027', icon: 'medication' },
      { name: 'Halls Honey Lemon', dose: '1 box', price: 4.99, qty: 1, packed: true, expiry: '09/2026', icon: 'bottleA' },
      { name: 'Voltaren Emulgel', dose: '1 tube', price: 16.99, qty: 1, packed: false, expiry: '06/2026', icon: 'bottleA' },
      { name: 'Oral Rehydration Salts', dose: '5 packs', price: 6.99, qty: 5, packed: false, expiry: '01/2027', icon: 'bottleB' },
      { name: 'Vitamin B Complex', dose: '1 box', price: 7.99, qty: 1, packed: false, expiry: '12/2026', icon: 'medication' },
      { name: 'Delsym Cough Syrup', dose: '1 bottle', price: 10.99, qty: 1, packed: false, expiry: '10/2026', icon: 'bottleA' },
      { name: 'Saline 0.9%', dose: '2 bottles', price: 6.99, qty: 2, packed: false, expiry: '08/2027', icon: 'bottleB' },
      { name: 'Cetirizine 10mg', dose: '1 box', price: 9.99, qty: 1, packed: false, expiry: '11/2026', icon: 'medication' },
      { name: 'Omeprazole 20mg', dose: '14 caps', price: 13.99, qty: 14, packed: false, expiry: '07/2026', icon: 'dot' },
      { name: 'Loperamide 2mg', dose: '1 card', price: 6.99, qty: 1, packed: false, expiry: '02/2027', icon: 'medication' },
      { name: 'Pedialyte ORS Kids', dose: '4 packs', price: 8.99, qty: 4, packed: false, expiry: '09/2027', icon: 'bottleB' },
      { name: 'Florastor Probiotic', dose: '10 sachets', price: 14.99, qty: 10, packed: false, expiry: '05/2027', icon: 'pills' },
      { name: 'Acetaminophen 500mg', dose: '1 box', price: 5.99, qty: 1, packed: false, expiry: '03/2027', icon: 'medication' },
      { name: 'Kaopectate Orange', dose: '6 sachets', price: 9.99, qty: 6, packed: false, expiry: '04/2027', icon: 'dot' },
      { name: 'Liquid IV Electrolyte', dose: '6 packs', price: 9.99, qty: 6, packed: false, expiry: '01/2028', icon: 'bottleB' },
      { name: 'Carlson Kids DHA', dose: '1 box', price: 16.99, qty: 1, packed: false, expiry: '06/2028', icon: 'medication' },
      { name: 'Magnesium B6', dose: '1 box', price: 12.99, qty: 1, packed: false, expiry: '09/2027', icon: 'medication' },
      { name: 'Gaviscon Sachet', dose: '12 sachets', price: 14.99, qty: 12, packed: false, expiry: '12/2027', icon: 'bottleA' },
      { name: 'Systane Eye Drops', dose: '1 bottle', price: 12.99, qty: 1, packed: false, expiry: '11/2027', icon: 'medication' },
      { name: 'Purell Hand Sanitizer 60ml', dose: '1 bottle', price: 3.99, qty: 1, packed: false, expiry: '03/2029', icon: 'bottleA' },
    ],
    note: 'Please leave all medicine labels visible in one bag and keep the syrup upright. Buyer may request partial handoff if courier arrives during office check-in period, so call 5 minutes before drop-off and confirm package count before handing over.',
    actionType: 'ready',
  },
  {
    id: 'RX-003', customer: 'Sarah Williams', phone: '(312) 555-0268',
    address: '225 N Michigan Ave, Chicago, IL 60601', deliveryType: 'pickup', courier: null,
    status: 'ready', payStatus: 'paid', payMethod: 'Apple Pay',
    hasRx: true, rxStatus: 'approved',
    total: 179.98, deliveryFee: 0, time: '8:55 AM', timeAgo: '46m ago', phase: 3,
    msgs: [
      { from: 'buyer', text: 'I\'ll be there in 10 minutes — which counter do I go to?', time: '9:38', unread: true },
    ],
    items: [
      { name: 'Metformin 500mg', dose: '60 tabs', price: 89.99, qty: 60, packed: true, expiry: '11/2026', icon: 'medication' },
      { name: 'Rosuvastatin 10mg', dose: '30 tabs', price: 89.99, qty: 30, packed: true, expiry: '01/2027', icon: 'medication' },
    ],
    note: 'Walk-in pickup. Show order QR at counter 3.',
    actionType: 'handoff',
  },
  {
    id: 'RX-004', customer: 'James Chen', phone: '(714) 555-0312',
    address: '200 Harbor Blvd, Anaheim, CA 92802', deliveryType: 'courier', courier: 'DoorDash',
    status: 'new', payStatus: 'unpaid', payMethod: 'Zelle',
    hasRx: false, rxStatus: null,
    total: 34.99, deliveryFee: 6.99, time: '9:40 AM', timeAgo: '1m ago', phase: 0,
    msgs: [
      { from: 'buyer', text: 'Just sent the payment — here\'s the screenshot 📷', time: '9:41', unread: true },
    ],
    items: [
      { name: 'Nexium 20mg', dose: '14 caps', price: 34.99, qty: 14, packed: false, expiry: '04/2026', icon: 'dot' },
    ],
    note: 'Awaiting Zelle transfer. Buyer claims sent.',
    actionType: 'verify-pay',
  },
  {
    id: 'RX-005', customer: 'Patricia Thompson', phone: '(404) 555-0198',
    address: '33 Peachtree St NE, Atlanta, GA 30303', deliveryType: 'courier', courier: 'FedEx',
    status: 'preparing', payStatus: 'paid', payMethod: 'Venmo',
    hasRx: true, rxStatus: 'approved',
    total: 489.98, deliveryFee: 9.99, time: '9:15 AM', timeAgo: '26m ago', phase: 2,
    msgs: [],
    items: [
      { name: 'Humira 40mg Injection', dose: '2 pcs', price: 399.99, qty: 2, packed: true, expiry: '09/2025', icon: 'medication' },
      { name: 'BD Pen Needle 32G', dose: '1 box', price: 89.99, qty: 1, packed: true, expiry: '01/2028', icon: 'box' },
    ],
    note: 'Cold-chain. Keep 2–8°C until handoff.',
    actionType: 'ready',
  },
  {
    id: 'RX-006', customer: 'Robert Davis', phone: '(415) 555-0274',
    address: '7 Market St, San Francisco, CA 94105', deliveryType: 'courier', courier: 'Instacart',
    status: 'delivering', payStatus: 'paid', payMethod: 'Visa',
    hasRx: false, rxStatus: null,
    total: 64.98, deliveryFee: 6.99, time: '8:45 AM', timeAgo: '56m ago', phase: 4,
    msgs: [
      { from: 'pharmacy', text: 'Your order is ready. The driver is on their way.', time: '9:20', unread: false },
    ],
    items: [
      { name: 'Zyrtec 10mg', dose: '1 box', price: 34.99, qty: 1, packed: true, expiry: '07/2026', icon: 'medication' },
      { name: 'Flonase Nasal Spray', dose: '1 bottle', price: 29.99, qty: 1, packed: true, expiry: '05/2026', icon: 'bottleB' },
    ],
    note: null,
    actionType: 'deliver',
  },
  {
    id: 'RX-007', customer: 'Jennifer Martinez', phone: '(213) 555-0361',
    address: '120 Wilshire Blvd, Los Angeles, CA 90010', deliveryType: 'courier', courier: 'UPS',
    status: 'delivered', payStatus: 'paid', payMethod: 'Apple Pay',
    hasRx: false, rxStatus: null,
    total: 24.99, deliveryFee: 5.99, time: '8:10 AM', timeAgo: '1h 31m', phase: 5,
    msgs: [
      { from: 'buyer', text: 'Got it, thank you so much! 🙏', time: '8:42', unread: false },
    ],
    items: [
      { name: 'Emergen-C Performance', dose: '1 tube', price: 24.99, qty: 1, packed: true, expiry: '10/2026', icon: 'dot' },
    ],
    note: null,
    actionType: 'complete',
  },
  {
    id: 'RX-008', customer: 'David Anderson', phone: '(718) 555-0485',
    address: '56 Atlantic Ave, Brooklyn, NY 11201', deliveryType: 'pickup', courier: null,
    status: 'new', payStatus: 'paid', payMethod: 'Venmo',
    hasRx: true, rxStatus: 'pending',
    total: 219.98, deliveryFee: 0, time: '9:35 AM', timeAgo: '6m ago', phase: 0,
    msgs: [
      { from: 'buyer', text: 'The prescription was written by Dr. Johnson — I\'ll bring the original when I pick up.', time: '9:35', unread: true },
      { from: 'buyer', text: 'Here\'s a photo of the prescription 📷', time: '9:36', unread: true },
    ],
    items: [
      { name: 'Lantus SoloStar 100U/mL', dose: '1 pen', price: 109.99, qty: 1, packed: false, expiry: '11/2025', icon: 'medication' },
      { name: 'Novomix 30 FlexPen', dose: '1 pen', price: 109.99, qty: 1, packed: false, expiry: '10/2025', icon: 'medication' },
    ],
    note: 'Insulin — controlled substance. Verify prescribing doctor license.',
    actionType: 'accept',
  },
  {
    id: 'RX-009', customer: 'Karen Wilson', phone: '(202) 555-0137',
    address: '89 Pennsylvania Ave NW, Washington, DC 20004', deliveryType: 'courier', courier: 'UPS',
    status: 'completed', payStatus: 'paid', payMethod: 'Visa',
    hasRx: false, rxStatus: null,
    total: 19.98, deliveryFee: 5.99, time: '7:55 AM', timeAgo: '1h 46m', phase: 6,
    msgs: [],
    items: [
      { name: 'DayQuil Severe', dose: '1 box', price: 12.99, qty: 1, packed: true, expiry: '08/2026', icon: 'medication' },
      { name: 'Afrin Nasal Spray', dose: '1 bottle', price: 6.99, qty: 1, packed: true, expiry: '02/2027', icon: 'bottleB' },
    ],
    note: null,
    actionType: 'done',
  },
];
