import { foundationCssVars } from './tokens/foundation';
import { semanticCssVars }   from './tokens/semantic';
import { componentCssVars }  from './tokens/component';

function toRootBlock(
  vars:    Record<string, string | number>,
  comment: string,
): string {
  const header = `/* ${comment} */\n/* Generated by scripts/render-token-css.cjs — do not edit directly. */`;
  const lines  = Object.entries(vars)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n');
  return `${header}\n:root {\n${lines}\n}\n`;
}

export function generateFoundationCss(): string {
  return toRootBlock(
    foundationCssVars as Record<string, string | number>,
    'Foundation layer (--f-*): raw visual primitives. Only layer allowed to contain hard-coded values.',
  );
}

export function generateSemanticCss(): string {
  return toRootBlock(
    semanticCssVars as Record<string, string | number>,
    'Semantic layer (--s-*): interface meaning. Values reference --f-* vars only.',
  );
}

export function generateComponentCss(): string {
  return toRootBlock(
    componentCssVars as Record<string, string | number>,
    'Component layer (--c-*): component-scoped layout and control decisions.',
  );
}
